import { auth } from "@/lib/auth"
import { prisma } from "@/lib/prisma"

export async function GET(req: Request) {
  const session = await auth()
  if (session?.user?.role !== "SUPERADMIN") {
    return Response.json({ error: "No autorizado" }, { status: 403 })
  }

  const pwd = new URL(req.url).searchParams.get("pwd")
  if (!pwd || pwd !== process.env.BACKUP_PASSWORD) {
    return Response.json({ error: "Contrasena incorrecta" }, { status: 401 })
  }

  const [
    systemConfigs,
    documentCategories,
    eppCatalog,
    permissions,
    verificationTokens,
    departments,
    roles,
    rolePermissions,
    users,
    employees,
    accounts,
    sessions,
    auditLogs,
    documents,
    equipment,
    tools,
    announcements,
    projects,
    documentVersions,
    documentPermissions,
    overtimeRecords,
    hoursBank,
    timeOffRequests,
    vacationRequests,
    attendance,
    dc3Records,
    eppRecords,
    purchaseRequisitions,
    vales,
    toolCheckouts,
    equipmentLogs,
    repairRequests,
    projectTasks,
    projectPhotos,
    projectUpdates,
    projectForms,
    checkLists,
    checkListItems,
    clientSurveys,
    onboardings,
    onboardingItems,
  ] = await Promise.all([
    prisma.systemConfig.findMany(),
    prisma.documentCategory.findMany(),
    prisma.ePPCatalog.findMany(),
    prisma.permission.findMany(),
    prisma.verificationToken.findMany(),
    prisma.department.findMany(),
    prisma.role.findMany(),
    prisma.rolePermission.findMany(),
    prisma.user.findMany(),
    prisma.employee.findMany(),
    prisma.account.findMany(),
    prisma.session.findMany(),
    prisma.auditLog.findMany(),
    prisma.document.findMany(),
    prisma.equipment.findMany(),
    prisma.tool.findMany(),
    prisma.announcement.findMany(),
    prisma.project.findMany(),
    prisma.documentVersion.findMany(),
    prisma.documentPermission.findMany(),
    prisma.overtimeRecord.findMany(),
    prisma.hoursBank.findMany(),
    prisma.timeOffRequest.findMany(),
    prisma.vacationRequest.findMany(),
    prisma.attendance.findMany(),
    prisma.dC3Record.findMany(),
    prisma.ePPRecord.findMany(),
    prisma.purchaseRequisition.findMany(),
    prisma.vale.findMany(),
    prisma.toolCheckout.findMany(),
    prisma.equipmentLog.findMany(),
    prisma.repairRequest.findMany(),
    prisma.projectTask.findMany(),
    prisma.projectPhoto.findMany(),
    prisma.projectUpdate.findMany(),
    prisma.projectForm.findMany(),
    prisma.checkList.findMany(),
    prisma.checkListItem.findMany(),
    prisma.clientSurvey.findMany(),
    prisma.onboarding.findMany(),
    prisma.onboardingItem.findMany(),
  ])

  const backup = {
    version: "1.0",
    timestamp: new Date().toISOString(),
    systemConfigs,
    documentCategories,
    eppCatalog,
    permissions,
    verificationTokens,
    departments,
    roles,
    rolePermissions,
    users,
    employees,
    accounts,
    sessions,
    auditLogs,
    documents,
    equipment,
    tools,
    announcements,
    projects,
    documentVersions,
    documentPermissions,
    overtimeRecords,
    hoursBank,
    timeOffRequests,
    vacationRequests,
    attendance,
    dc3Records,
    eppRecords,
    purchaseRequisitions,
    vales,
    toolCheckouts,
    equipmentLogs,
    repairRequests,
    projectTasks,
    projectPhotos,
    projectUpdates,
    projectForms,
    checkLists,
    checkListItems,
    clientSurveys,
    onboardings,
    onboardingItems,
  }

  const date = new Date().toISOString().split("T")[0]
  return new Response(JSON.stringify(backup, null, 2), {
    headers: {
      "Content-Type": "application/json",
      "Content-Disposition": `attachment; filename="backup-rim-${date}.json"`,
    },
  })
}
